### ISSUE TITLE
Error: error building site: render: failed to render pages: render of "home" failed

### ISSUE THREAD

**Issue by Keddy54** [zetxek/adritian-free-hugo-theme#8] opened 2024-01-16 13:37 UTC
Following the steps outlined in the README I get the following error:

Hugo version:
> Start building sites … 
> hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended darwin/amd64 BuildDate=2024-01-05T12:21:15Z VendorInfo=brew

Error log:

> WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
> Built in 47 ms
> Error: error building site: render: failed to render pages: render of "home" failed: "/Users/iatomic/Documents/warranty54/test/tester/themes/adritian-free-hugo-theme/layouts/index.html:7:7": execute of template failed: template: index.html:7:7: executing "index.html" at <partial "head.html" .>: error calling partial: "/Users/iatomic/Documents/warranty54/test/tester/themes/adritian-free-hugo-theme/layouts/partials/head.html:11:60": execute of template failed: template: partials/head.html:11:60: executing "partials/head.html" at <resources.ToCSS>: error calling ToCSS: type <nil> not supported in Resource transformations

**Comment by usmimukherjee** [comment] 2024-01-16 15:23
Hi, 
I am also facing the same issue on Ubuntu:

Log:
usmi@Usmi-PC:/mnt/c/Users/usmim/usmi-webpage/usmimukherjee$ hugo server -D -v
Start building sites … 
hugo v0.92.2+extended linux/amd64 BuildDate=2023-01-31T11:11:57Z VendorInfo=ubuntu:0.92.2-1ubuntu0.1
INFO 2024/01/16 11:15:58 syncing static files to /
WARN 2024/01/16 11:15:58 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/01/16 11:15:58 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
Error: Error building site: failed to render pages: render of "home" failed: execute of template failed: template: index.html:7:7: executing "index.html" at <partial "head.html" .>: error calling partial: "/mnt/c/Users/usmim/usmi-webpage/usmimukherjee/themes/adritian-free-hugo-theme/layouts/partials/head.html:11:60": execute of template failed: template: partials/head.html:11:60: executing "partials/head.html" at <resources.ToCSS>: error calling ToCSS: type <nil> not supported in Resource transformations
Built in 4776 ms

**Comment by tonhe** [comment] 2024-02-03 16:09
Same issue here --  I'm new to hugo but the issue seems to be a missing file critical.css

**Comment by s4ln1x** [comment] 2024-02-06 09:28
Same issue on Fedora 39

```shell
> hugo server
Start building sites … 
hugo v0.111.3+extended linux/amd64 BuildDate=2023-07-26T00:00:00+00:00 VendorInfo=Fedora:0.111.3-4.fc39
WARN 2024/02/06 03:19:32 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
WARN 2024/02/06 03:19:32 found no layout file for "HTML" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
Error: Error building site: failed to render pages: render of "home" failed: "/home/baki/r/my-website-1/themes/adritian-free-hugo-theme/layouts/index.html:7:7": execute of template failed: template: index.html:7:7: executing "index.html" at <partial "head.html" .>: error calling partial: "/home/baki/r/my-website-1/themes/adritian-free-hugo-theme/layouts/partials/head.html:11:60": execute of template failed: template: partials/head.html:11:60: executing "partials/head.html" at <resources.ToCSS>: error calling ToCSS: type <nil> not supported in Resource transformations
Built in 29 ms
```

### Reproduction steps

```shell
dnf install -y hugo
hugo new site my-site
cd my-site
git init
git submodule add https://github.com/zetxek/adritian-free-hugo-theme.git themes/adritian-free-hugo-theme
echo "theme = 'adritian-free-hugo-theme'" >> hugo.toml
hugo server
```

**Comment by andrewfn** [comment] 2024-02-08 02:17
I'm getting the same error message as usmimukherjee, also on Ubuntu

**Comment by zetxek** [comment] 2024-02-11 17:42
I had not noticed the issue - I'll try to look into it 🕵️‍♂️

I suspect some missing steps in setting up the Javascript files. While I look into it - feel free to check in https://github.com/zetxek/adrianmoreno.info, as I use the theme there too (or take files if you need them/might fix the problem).

**Comment by zetxek** [comment] 2024-02-11 19:05
I've reproduced it:

```
➜  ~ hugo new site adritian-demo
Congratulations! Your new Hugo site was created in /Users/adrianmorenopena/adritian-demo.

Just a few more steps...

1. Change the current directory to /Users/adrianmorenopena/adritian-demo.
2. Create or install a theme:
   - Create a new theme with the command "hugo new theme <THEMENAME>"
   - Install a theme from https://themes.gohugo.io/
3. Edit hugo.toml, setting the "theme" property to the theme name.
4. Create new content with the command "hugo new content <SECTIONNAME>/<FILENAME>.<FORMAT>".
5. Start the embedded web server with the command "hugo server --buildDrafts".

See documentation at https://gohugo.io/.
➜  ~ cd adritian-demo
➜  adritian-demo ls
archetypes assets     content    data       hugo.toml  i18n       layouts    static     themes
➜  adritian-demo git init
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /Users/adrianmorenopena/adritian-demo/.git/

➜  adritian-demo git:(master) ✗ git submodule add https://github.com/zetxek/adritian-free-hugo-theme.git themes/adritian
Cloning into '/Users/adrianmorenopena/adritian-demo/themes/adritian'...
remote: Enumerating objects: 479, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (81/81), done.
remote: Total 479 (delta 72), reused 74 (delta 53), pack-reused 344
Receiving objects: 100% (479/479), 9.68 MiB | 12.26 MiB/s, done.
Resolving deltas: 100% (134/134), done.
➜  adritian-demo git:(master) ✗ echo "theme = 'adritian'" >> hugo.toml
➜  adritian-demo git:(master) ✗ hugo server
Watching for changes in /Users/adrianmorenopena/adritian-demo/{archetypes,assets,content,data,i18n,layouts,static,themes}
Watching for config changes in /Users/adrianmorenopena/adritian-demo/hugo.toml
Start building sites …
hugo v0.122.0-b9a03bd59d5f71a529acb3e33f995e0ef332b3aa+extended darwin/arm64 BuildDate=2024-01-26T15:54:24Z VendorInfo=brew

WARN  found no layout file for "html" for kind "taxonomy": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
Built in 53 ms
Error: error building site: render: failed to render pages: render of "home" failed: "/Users/adrianmorenopena/adritian-demo/themes/adritian/layouts/index.html:7:7": execute of template failed: template: index.html:7:7: executing "index.html" at <partial "head.html" .>: error calling partial: "/Users/adrianmorenopena/adritian-demo/themes/adritian/layouts/partials/head.html:11:60": execute of template failed: template: partials/head.html:11:60: executing "partials/head.html" at <resources.ToCSS>: error calling ToCSS: type <nil> not supported in Resource transformations
```

**Comment by Ceesaxp** [comment] 2024-02-11 20:30
For some reason Hugo fails to locate the CSS files correctly. I've worked-around this with a crude hack of wrapping `$cssBundle` in a bunch of conditionals, like so:

```
{{ $cssBundle := slice }}
{{ range .Site.Params.plugins.css }}
    {{ if findRE "^http" .link }}
        <link rel="stylesheet" href="{{ .link | absURL }}">
    {{ else }}
        {{ $cssFile := resources.Get .link }}
        {{ if $cssFile }}
            {{ $cssBundle = $cssBundle | append $cssFile }}
        {{ end }}
    {{ end }}
{{ end }}
{{ if ne (len $cssBundle) 0 }}
    {{ $cssBundle = $cssBundle | resources.Concat "css/bundle.css" }}
{{ end }}
```
But it is just that – a hack…

Also, I've had to copy everything in `/static` to `/assets` for other partials to work.

Lastly – you may need to add the `npm install postcss-cli`, as otherwise PostCSS pipes are failing too…

**Comment by Ceesaxp** [comment] 2024-02-11 20:32
> Same issue here -- I'm new to hugo but the issue seems to be a missing file critical.css
> 
> From layouts/partials/head.html `{{ $critical := resources.Get "css/critical.css" | resources.ToCSS | resources.Minify }}`

Just do a `touch assets/css/critical.css` from the theme directory… While you're at it – also do the same for `bundle.css`

**Comment by zetxek** [comment] 2024-02-11 20:33
Yes! I want the theme to use the resources system in hugo, but accessing them from the theme (as in opposition from the top-level folders/files as with my own site) is giving some issues.

Thanks for sharing the snippet @Ceesaxp  - that's the part that I'm debugging. I'm thinking of a first fix by having the references to the existing files, and then look into piping them "properly".

**Comment by Ceesaxp** [comment] 2024-02-11 21:01
Hey, I think that partial fix is in the PR…

**Closed** 2024-02-11 21:56 UTC

**Comment by zetxek** [comment] 2024-02-11 22:07
Thanks @Ceesaxp for the bugfix - I have also added some improvements in documentation and "out of the box demo" in https://github.com/zetxek/adritian-free-hugo-theme/pull/11.

@andrewfn @s4ln1x @tonhe @usmimukherjee @Keddy54 feel free to give a try again (if you didn't gave up on the theme 😅), and create issues for anything else you see as improvements, or that is not working ok!
